// @ts-check
/**
 * contrast.mjs — WCAG contrast audit across every theme and colour mode.
 *
 * Not a node:test file: it needs a real browser, because the palette is
 * generated by OKLCH expressions that only a CSS engine can resolve. Run it
 * against a served copy of the app:
 *
 *     python3 -m http.server 8099 &
 *     node test/contrast.mjs http://127.0.0.1:8099
 *
 * Checks, for all 14 themes in both light and dark:
 *   --ink  on --surface   >= 4.5:1   (body text, WCAG 1.4.3)
 *   --ink-2 on --surface  >= 4.5:1   (secondary text)
 *   --ink  on --card      >= 4.5:1   (text on cards)
 *   --line on --surface   >= 3.0:1   (borders, icons, chart marks, 1.4.11)
 *
 * Exits non-zero on any failure, so it can gate a commit.
 */

import pw from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pw;

const BASE = process.argv[2] || 'http://127.0.0.1:8099';

const THEMES = [
  'hellokitty', 'mymelody', 'kuromi', 'cinnamoroll', 'keroppi', 'gudetama',
  'twinstars', 'badtzmaru', 'chococat', 'pompompurin', 'aggretsuko',
  'pochacco', 'hangyodon', 'plain',
];

/** [foreground token, background token, minimum ratio, label] */
const CHECKS = [
  ['--ink', '--surface', 4.5, 'body text on surface'],
  ['--ink-2', '--surface', 4.5, 'secondary text on surface'],
  ['--ink', '--card', 4.5, 'body text on card'],
  ['--ink-3', '--card', 3.0, 'tertiary text on card'],
  ['--line', '--surface', 3.0, 'border on surface'],
  // --primary is a fill and is deliberately not checked at 3:1; --primary-line
  // is the token used wherever a control's boundary has to meet WCAG 1.4.11.
  ['--primary-line', '--surface', 3.0, 'control boundary on surface'],
  ['--on-primary', '--primary', 4.5, 'label on a primary button'],
  // The week strip's tick sits on a logged day, which is --surface-2. It is a
  // glyph carrying meaning, so it is held to the text bar rather than 3:1.
  // The same pair carries the standing-note icon and its left edge.
  ['--primary-line', '--surface-2', 4.5, 'logged tick and note icon on surface-2'],
  ['--ink', '--surface-2', 4.5, 'note body text'],
  /*
    Secondary text moved onto surface-2 when the "worth knowing" cards dropped
    to the quiet tier, so the pair it is actually drawn on now has to be
    checked. Adding the pair rather than trusting that surface-2 is close
    enough to surface: they are different tokens with different lightness in
    both modes, and "close enough" is how a ratio quietly slips under.
  */
  ['--ink-2', '--surface-2', 4.5, 'secondary text on the quiet card tier'],
  // The one destructive button in the app. Held to the text bar, not 3:1.
  ['--on-danger', '--danger-solid', 4.5, 'label on the erase button'],
  /*
    Calendar day numbers sit on the phase fills, and those two pairs were the
    gap in this list: every check above is text on a *surface* token, but a
    third of the days in any month are drawn on `--fertile-soft` or
    `--luteal-soft` instead. The separation block below proves the fills are
    distinguishable from each other and says nothing about whether the date
    written inside one is readable.

    Worth pinning rather than eyeballing, because both fills are derived from
    `--c-cycle` — anyone retuning the cycle palette's saturation moves the
    background under these digits without touching anything named "text".
  */
  ['--ink', '--fertile-soft', 4.5, 'a date on a fertile day'],
  ['--ink', '--luteal-soft', 4.5, 'a date on a luteal day'],
];

/** sRGB relative luminance, per WCAG 2.x. @param {number[]} rgb 0-255 */
function luminance([r, g, b]) {
  const channel = (/** @type {number} */ v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

/** @param {number[]} a @param {number[]} b */
function ratio(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la > lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

/**
 * Cycle colours that have to stay distinguishable *from each other*.
 *
 * Contrast against a background says nothing about this, and it is what breaks
 * when saturation is tuned: the cycle palette's chroma is now derived from the
 * theme's rather than pinned, which is what stops the ring reading as a chart
 * from another app — and which, pushed too far, would quietly turn a period
 * day and a luteal day into the same circle.
 *
 * Pairs, not a cross product. `--period-pred` is deliberately the same hue as
 * `--period` and is told apart by being a dashed outline against a filled
 * circle; demanding a colour gap there would be measuring the wrong thing and
 * would force the two apart for no one's benefit. Listed here are the pairs
 * where colour is the only thing doing the work: filled calendar circles that
 * appear in the same month, and solid arcs that touch on the ring.
 *
 * Measured in OKLab, where a fixed distance means roughly the same perceptual
 * difference anywhere in the space — the reason the palette is authored in
 * OKLCH to begin with. 0.09 is comfortably past "these are two colours"
 * without demanding the loud separation the palette used to have.
 */
const MIN_CYCLE_SEPARATION = 0.09;

const CYCLE_PAIRS = [
  ['--period', '--fertile'],
  ['--period', '--ovulation'],
  ['--period', '--luteal'],
  ['--fertile', '--ovulation'],
  ['--fertile', '--luteal'],
  ['--ovulation', '--luteal'],
];

const CYCLE_TOKENS = [...new Set(CYCLE_PAIRS.flat())];

const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
});
const page = await browser.newPage();
await page.goto(BASE, { waitUntil: 'domcontentloaded' });

/** @type {{theme: string, mode: string, label: string, got: number, want: number}[]} */
const failures = [];
let checked = 0;

for (const theme of THEMES) {
  for (const mode of ['light', 'dark']) {
    /** @type {Record<string, number[]>} */
    const resolved = await page.evaluate(
      ({ theme, mode, tokens }) => {
        const root = document.documentElement;
        root.dataset.theme = theme;
        root.dataset.mode = mode;

        const probe = document.createElement('span');
        probe.style.display = 'none';
        document.body.append(probe);

        // Chromium reports computed colours in their authored space, so
        // getComputedStyle returns "oklch(0.32 0.07 305)" rather than rgb().
        // Painting each colour onto a 1×1 canvas and reading the pixel gets
        // the real sRGB bytes — and applies the same gamut clipping the user
        // will actually see, which parsing the string would miss.
        const canvas = document.createElement('canvas');
        canvas.width = canvas.height = 1;
        const ctx = canvas.getContext('2d', { willReadFrequently: true });

        /** @type {Record<string, number[]>} */
        const out = {};
        for (const token of tokens) {
          probe.style.color = `var(${token})`;
          const computed = getComputedStyle(probe).color;

          ctx.clearRect(0, 0, 1, 1);
          ctx.fillStyle = '#000';
          ctx.fillStyle = computed;      // ignored if the browser can't parse it
          ctx.fillRect(0, 0, 1, 1);
          const [r, g, b] = ctx.getImageData(0, 0, 1, 1).data;
          out[token] = [r, g, b];
        }

        probe.remove();
        return out;
      },
      { theme, mode, tokens: [...new Set(CHECKS.flatMap((c) => [c[0], c[1]]))] },
    );

    for (const [fg, bg, min, label] of CHECKS) {
      const got = ratio(resolved[String(fg)], resolved[String(bg)]);
      checked++;
      if (got < Number(min)) {
        failures.push({ theme, mode, label: String(label), got, want: Number(min) });
      }
    }

    /*
      The phase block's wash is a composite, so no pair of tokens describes it.

      It is `color-mix(phase 12%, card)` with the phase colour set from the
      same token the ring arc uses, which means four different backgrounds per
      theme per mode — and the menstrual one is the strongest colour in the
      palette. Reasoning that 12% "barely moves it" is exactly the sort of
      thing that turns out to be wrong on one theme in dark mode, so it gets
      measured.

      Through the same canvas as everything else above: a first attempt read
      `backgroundColor` and pulled digits out of it with a regex, which for a
      `color-mix` Chromium reports as `oklab(...)` — so it scored the app
      against numbers that were not colours and failed a hundred pairs that
      were fine.
    */
    const washes = await page.evaluate(
      ({ theme, mode, phases }) => {
        const root = document.documentElement;
        root.dataset.theme = theme;
        root.dataset.mode = mode;

        const probe = document.createElement('span');
        probe.style.display = 'none';
        document.body.append(probe);

        const canvas = document.createElement('canvas');
        canvas.width = canvas.height = 1;
        const ctx = canvas.getContext('2d', { willReadFrequently: true });

        /** @type {Record<string, number[]>} */
        const out = {};
        for (const token of phases) {
          probe.style.color = `color-mix(in oklab, var(${token}) 12%, var(--card))`;
          const computed = getComputedStyle(probe).color;
          ctx.clearRect(0, 0, 1, 1);
          ctx.fillStyle = '#000';
          ctx.fillStyle = computed;
          ctx.fillRect(0, 0, 1, 1);
          const [r, g, b] = ctx.getImageData(0, 0, 1, 1).data;
          out[token] = [r, g, b];
        }

        probe.remove();
        return out;
      },
      { theme, mode, phases: ['--period', '--fertile-soft', '--ovulation', '--luteal'] },
    );

    for (const [token, mixed] of Object.entries(washes)) {
      for (const [fg, min, what] of [['--ink', 4.5, 'heading'], ['--ink-2', 4.5, 'body']]) {
        const got = ratio(resolved[String(fg)], mixed);
        checked++;
        if (got < Number(min)) {
          failures.push({ theme, mode, got, want: Number(min),
            label: `phase-block ${what} text on a ${token} wash` });
        }
      }
    }

    /*
      The cycle colours have to stay distinguishable from *each other*.

      Contrast against a background says nothing about this, and it is the
      thing that breaks when saturation is tuned: the cycle palette's chroma is
      now derived from the theme's rather than pinned, which is what stops the
      ring reading as a chart from another app — and which, taken too far or
      applied to an already-desaturated theme, would quietly turn a period day
      and a luteal day into the same grey circle.

      Measured in OKLab, where a fixed numeric distance means roughly the same
      perceptual difference anywhere in the space, which is the entire reason
      the palette is authored in OKLCH to begin with.
    */
    const cycleColours = await page.evaluate(
      ({ theme, mode, tokens }) => {
        const root = document.documentElement;
        root.dataset.theme = theme;
        root.dataset.mode = mode;

        const probe = document.createElement('span');
        probe.style.display = 'none';
        document.body.append(probe);

        /** @type {Record<string, number[]>} */
        const out = {};
        for (const token of tokens) {
          // Straight to OKLab: no canvas, because this is about perceptual
          // distance rather than the sRGB bytes a contrast ratio needs.
          probe.style.color = `oklab(from var(${token}) l a b)`;
          const m = getComputedStyle(probe).color.match(/-?[\d.]+/g) ?? [];
          out[token] = m.slice(0, 3).map(Number);
        }
        probe.remove();
        return out;
      },
      { theme, mode, tokens: CYCLE_TOKENS },
    );

    for (const [an, bn] of CYCLE_PAIRS) {
      const a = cycleColours[an];
      const b = cycleColours[bn];
      const dist = Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
      checked++;
      if (dist < MIN_CYCLE_SEPARATION) {
        failures.push({ theme, mode, got: dist, want: MIN_CYCLE_SEPARATION,
          label: `${an} vs ${bn} too alike`, unit: 'ΔOKLab' });
      }
    }
  }
}

await browser.close();

console.log(`contrast: ${checked} pairs checked across ${THEMES.length} themes × 2 modes`);

if (failures.length) {
  console.log(`\n${failures.length} FAILED:\n`);
  for (const f of failures) {
    console.log(
      `  ${f.theme.padEnd(12)} ${f.mode.padEnd(5)} ${f.label.padEnd(30)} `
      // Parenthesised: `+` binds tighter than `===`, so without these the
      // label was concatenated into the comparison and silently discarded,
      // and every failure printed as a bare number with no name on it.
      + (f.unit === 'ΔOKLab'
        ? `${f.got.toFixed(3)}  (needs ${f.want})`
        : `${f.got.toFixed(2)}:1  (needs ${f.want}:1)`),
    );
  }
  process.exit(1);
}

console.log('all pairs pass');
