// @ts-check
/**
 * contrast.mjs — WCAG contrast audit across every theme and colour mode.
 *
 * Not a node:test file: it needs a real browser, because the palette is
 * generated by OKLCH expressions that only a CSS engine can resolve. Run it
 * against a served copy of the app:
 *
 *     python3 -m http.server 8099 &
 *     node test/contrast.mjs http://127.0.0.1:8099
 *
 * Checks, for all 14 themes in both light and dark:
 *   --ink  on --surface   >= 4.5:1   (body text, WCAG 1.4.3)
 *   --ink-2 on --surface  >= 4.5:1   (secondary text)
 *   --ink  on --card      >= 4.5:1   (text on cards)
 *   --line on --surface   >= 3.0:1   (borders, icons, chart marks, 1.4.11)
 *
 * Exits non-zero on any failure, so it can gate a commit.
 */

import pw from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pw;

const BASE = process.argv[2] || 'http://127.0.0.1:8099';

const THEMES = [
  'hellokitty', 'mymelody', 'kuromi', 'cinnamoroll', 'keroppi', 'gudetama',
  'twinstars', 'badtzmaru', 'chococat', 'pompompurin', 'aggretsuko',
  'pochacco', 'hangyodon', 'plain',
];

/** [foreground token, background token, minimum ratio, label] */
const CHECKS = [
  ['--ink', '--surface', 4.5, 'body text on surface'],
  ['--ink-2', '--surface', 4.5, 'secondary text on surface'],
  ['--ink', '--card', 4.5, 'body text on card'],
  ['--ink-3', '--card', 3.0, 'tertiary text on card'],
  ['--line', '--surface', 3.0, 'border on surface'],
  // --primary is a fill and is deliberately not checked at 3:1; --primary-line
  // is the token used wherever a control's boundary has to meet WCAG 1.4.11.
  ['--primary-line', '--surface', 3.0, 'control boundary on surface'],
  ['--on-primary', '--primary', 4.5, 'label on a primary button'],
  // The week strip's tick sits on a logged day, which is --surface-2. It is a
  // glyph carrying meaning, so it is held to the text bar rather than 3:1.
  // The same pair carries the standing-note icon and its left edge.
  ['--primary-line', '--surface-2', 4.5, 'logged tick and note icon on surface-2'],
  ['--ink', '--surface-2', 4.5, 'note body text'],
  // The one destructive button in the app. Held to the text bar, not 3:1.
  ['--on-danger', '--danger-solid', 4.5, 'label on the erase button'],
];

/** sRGB relative luminance, per WCAG 2.x. @param {number[]} rgb 0-255 */
function luminance([r, g, b]) {
  const channel = (/** @type {number} */ v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

/** @param {number[]} a @param {number[]} b */
function ratio(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la > lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

const browser = await chromium.launch({
  executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
});
const page = await browser.newPage();
await page.goto(BASE, { waitUntil: 'domcontentloaded' });

/** @type {{theme: string, mode: string, label: string, got: number, want: number}[]} */
const failures = [];
let checked = 0;

for (const theme of THEMES) {
  for (const mode of ['light', 'dark']) {
    /** @type {Record<string, number[]>} */
    const resolved = await page.evaluate(
      ({ theme, mode, tokens }) => {
        const root = document.documentElement;
        root.dataset.theme = theme;
        root.dataset.mode = mode;

        const probe = document.createElement('span');
        probe.style.display = 'none';
        document.body.append(probe);

        // Chromium reports computed colours in their authored space, so
        // getComputedStyle returns "oklch(0.32 0.07 305)" rather than rgb().
        // Painting each colour onto a 1×1 canvas and reading the pixel gets
        // the real sRGB bytes — and applies the same gamut clipping the user
        // will actually see, which parsing the string would miss.
        const canvas = document.createElement('canvas');
        canvas.width = canvas.height = 1;
        const ctx = canvas.getContext('2d', { willReadFrequently: true });

        /** @type {Record<string, number[]>} */
        const out = {};
        for (const token of tokens) {
          probe.style.color = `var(${token})`;
          const computed = getComputedStyle(probe).color;

          ctx.clearRect(0, 0, 1, 1);
          ctx.fillStyle = '#000';
          ctx.fillStyle = computed;      // ignored if the browser can't parse it
          ctx.fillRect(0, 0, 1, 1);
          const [r, g, b] = ctx.getImageData(0, 0, 1, 1).data;
          out[token] = [r, g, b];
        }

        probe.remove();
        return out;
      },
      { theme, mode, tokens: [...new Set(CHECKS.flatMap((c) => [c[0], c[1]]))] },
    );

    for (const [fg, bg, min, label] of CHECKS) {
      const got = ratio(resolved[String(fg)], resolved[String(bg)]);
      checked++;
      if (got < Number(min)) {
        failures.push({ theme, mode, label: String(label), got, want: Number(min) });
      }
    }
  }
}

await browser.close();

console.log(`contrast: ${checked} pairs checked across ${THEMES.length} themes × 2 modes`);

if (failures.length) {
  console.log(`\n${failures.length} FAILED:\n`);
  for (const f of failures) {
    console.log(
      `  ${f.theme.padEnd(12)} ${f.mode.padEnd(5)} ${f.label.padEnd(28)} ` +
      `${f.got.toFixed(2)}:1  (needs ${f.want}:1)`,
    );
  }
  process.exit(1);
}

console.log('all pairs pass');
